-- Super Simple Tables for Railway MySQL
-- One table at a time

CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  img VARCHAR(300) NOT NULL,
  href VARCHAR(300) NOT NULL
);

CREATE TABLE admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  task VARCHAR(100) NOT NULL,
  img VARCHAR(100) NOT NULL,
  token VARCHAR(100) NOT NULL,
  role VARCHAR(50) DEFAULT NULL
);

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  email VARCHAR(200) NOT NULL,
  phone VARCHAR(100) NOT NULL,
  city VARCHAR(100) NOT NULL,
  score INT NOT NULL,
  buy INT NOT NULL,
  role VARCHAR(50) DEFAULT 'USER'
);

CREATE TABLE monthlysales (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  price INT NOT NULL
);

CREATE TABLE products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(300) NOT NULL,
  price INT NOT NULL,
  score FLOAT NOT NULL,
  count INT NOT NULL,
  img VARCHAR(1000) NOT NULL,
  popularity INT NOT NULL,
  sale INT NOT NULL,
  colors INT NOT NULL,
  categoryID INT NOT NULL
);

CREATE TABLE comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userID INT NOT NULL,
  productID INT NOT NULL,
  score INT NOT NULL,
  date VARCHAR(50) NOT NULL,
  body TEXT NOT NULL,
  isAccept INT NOT NULL
);

CREATE TABLE offs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(20) NOT NULL,
  percent INT NOT NULL,
  productID INT NOT NULL,
  adminID INT NOT NULL,
  datetime DATETIME DEFAULT CURRENT_TIMESTAMP,
  max_use INT DEFAULT 1
);

CREATE TABLE orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  productID INT NOT NULL,
  userID INT NOT NULL,
  date VARCHAR(20) NOT NULL,
  hour VARCHAR(10) NOT NULL,
  popularity INT DEFAULT 0,
  sale INT DEFAULT 0
);